const state={data:null,view:"savings",scheme:"irp",compareType:"savings"};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const num=new Intl.NumberFormat("ko-KR");
const pct=v=>Number.isFinite(Number(v))?`${Number(v).toFixed(2)}%`:"—";
const money=v=>Number(v)>=1000000?`${(Number(v)/1000000).toFixed(1)}조`:`${num.format(Math.round(Number(v)||0))}억`;
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const returnOf=(row,period,scheme)=>scheme?Number(row[scheme]?.[`return${period}`]||0):Number(row[`return${period}`]||0);
const feeOf=(row,scheme)=>scheme?Number(row[scheme]?.fee||0):Number(row.fee||0);
const reserveOf=(row,scheme)=>scheme?Number(row[scheme]?.reserve||0):Number(row.reserve||0);

function showView(view){state.view=view;$$('.view-panel').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$$('[data-view-link]').forEach(x=>x.classList.toggle('active',x.dataset.viewLink===view));if(view==='compare')renderCompare();if(view==='tax')calculateTax();location.hash=view;window.scrollTo({top:$('.data-strip').offsetTop-70,behavior:'smooth'});}
$$('[data-view-link]').forEach(x=>x.addEventListener('click',e=>{e.preventDefault();showView(x.dataset.viewLink)}));

function areasFor(rows){return ['전체',...new Set(rows.map(r=>r.area).filter(Boolean))]}
function fillSelect(el,items){el.innerHTML=items.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}
function filtered(kind){const isSaving=kind==='savings', rows=isSaving?state.data.savings:state.data.retirement;const area=$(`#${kind}-area`).value,search=$(`#${kind}-search`).value.trim().toLowerCase(),period=$(`#${kind}-period`).value,metric=$(`#${kind}-metric`).value,scheme=isSaving?null:state.scheme;return rows.filter(r=>(area==='전체'||r.area===area)&&`${r.company} ${r.product||''}`.toLowerCase().includes(search)).sort((a,b)=>metric==='fee'?feeOf(a,scheme)-feeOf(b,scheme):metric==='reserve'?reserveOf(b,scheme)-reserveOf(a,scheme):returnOf(b,period,scheme)-returnOf(a,period,scheme));}
function topStats(rows,period,scheme,prefix){const best=[...rows].sort((a,b)=>returnOf(b,period,scheme)-returnOf(a,period,scheme))[0];const valid=rows.filter(r=>Number.isFinite(returnOf(r,period,scheme)));const avg=valid.length?valid.reduce((s,r)=>s+returnOf(r,period,scheme),0)/valid.length:0;const low=[...rows].filter(r=>feeOf(r,scheme)>0).sort((a,b)=>feeOf(a,scheme)-feeOf(b,scheme))[0];$(`#${prefix}-best`).textContent=best?pct(returnOf(best,period,scheme)):'—';$(`#${prefix}-best-name`).textContent=best?.company||'—';$(`#${prefix}-average`).textContent=pct(avg);$(`#${prefix}-low-fee`).textContent=low?pct(feeOf(low,scheme)):'—';$(`#${prefix}-low-fee-name`).textContent=low?.company||'—';}
function renderBars(el,rows,period,metric,scheme){const selected=[...rows].sort((a,b)=>metric==='fee'?feeOf(a,scheme)-feeOf(b,scheme):metric==='reserve'?reserveOf(b,scheme)-reserveOf(a,scheme):returnOf(b,period,scheme)-returnOf(a,period,scheme)).slice(0,9);const vals=selected.map(r=>metric==='fee'?feeOf(r,scheme):metric==='reserve'?reserveOf(r,scheme):returnOf(r,period,scheme));const max=Math.max(...vals,1),min=Math.min(...vals,0);el.innerHTML=selected.length?selected.map((r,i)=>{const v=vals[i],w=metric==='fee'?(max?((max-v)/(max-min||1)*75+20):50):Math.max(5,(v/max)*100),label=r.product?`${r.company} · ${r.product}`:r.company,value=metric==='fee'?pct(v):metric==='reserve'?money(v):pct(v);return `<div class="bar-row" title="${esc(label)}"><span class="bar-label">${esc(label)}</span><div class="bar-track"><div class="bar-fill" style="width:${w}%"></div></div><strong class="bar-value">${value}</strong></div>`}).join(''):'<div class="empty">조회 결과가 없습니다.</div>';}
function renderScatter(el,rows,period,scheme){el.querySelectorAll('.scatter-dot').forEach(x=>x.remove());const sample=rows.filter(r=>feeOf(r,scheme)>=0).slice(0,80);if(!sample.length)return;const returns=sample.map(r=>returnOf(r,period,scheme)),fees=sample.map(r=>feeOf(r,scheme));const rMin=Math.min(...returns),rMax=Math.max(...returns),fMin=Math.min(...fees),fMax=Math.max(...fees);sample.forEach(r=>{const dot=document.createElement('i');dot.className='scatter-dot';const x=5+((feeOf(r,scheme)-fMin)/(fMax-fMin||1))*90,y=5+((returnOf(r,period,scheme)-rMin)/(rMax-rMin||1))*90;dot.style.left=`${x}%`;dot.style.bottom=`${y}%`;dot.title=`${r.company}${r.product?' · '+r.product:''}\n수익률 ${pct(returnOf(r,period,scheme))} · 비용 ${pct(feeOf(r,scheme))}`;el.appendChild(dot)});}
function tableRows(rows,period,scheme){return rows.slice(0,80).map((r,i)=>`<tr><td><span class="rank ${i<3?'top':''}">${i+1}</span></td><td><strong>${esc(r.company)}</strong><small>${esc(r.product||'퇴직연금 사업자')}</small></td><td>${esc(r.area)}</td><td class="positive">${pct(returnOf(r,'3',scheme))}</td><td>${pct(returnOf(r,'5',scheme))}</td><td>${pct(returnOf(r,'10',scheme))}</td><td>${pct(feeOf(r,scheme))}</td><td>${money(reserveOf(r,scheme))}</td></tr>`).join('')||'<tr><td colspan="8" class="empty">조회 결과가 없습니다.</td></tr>'}
function renderSavings(){const rows=filtered('savings'),period=$('#savings-period').value,metric=$('#savings-metric').value;topStats(rows,period,null,'savings');renderBars($('#savings-bars'),rows,period,metric,null);renderScatter($('#savings-scatter'),rows,period,null);$('#savings-table').innerHTML=tableRows(rows,period,null);$('#savings-result-count').textContent=`${num.format(rows.length)}개 상품`;}
function renderRetirement(){const rows=filtered('retirement'),period=$('#retirement-period').value,metric=$('#retirement-metric').value;topStats(rows,period,state.scheme,'retirement');renderBars($('#retirement-bars'),rows,period,metric,state.scheme);renderScatter($('#retirement-scatter'),rows,period,state.scheme);$('#retirement-table').innerHTML=tableRows(rows,period,state.scheme);$('#retirement-result-count').textContent=`${num.format(rows.length)}개 사업자`;$('#retirement-chart-caption').textContent={irp:'개인형 IRP',dc:'DC형',db:'DB형'}[state.scheme];}
['savings-area','savings-period','savings-metric','savings-search'].forEach(id=>$(`#${id}`).addEventListener(id.includes('search')?'input':'change',renderSavings));
['retirement-area','retirement-period','retirement-metric','retirement-search'].forEach(id=>$(`#${id}`).addEventListener(id.includes('search')?'input':'change',renderRetirement));
$$('[data-scheme]').forEach(b=>b.addEventListener('click',()=>{$$('[data-scheme]').forEach(x=>x.classList.toggle('active',x===b));state.scheme=b.dataset.scheme;renderRetirement()}));

function compareRows(){return state.compareType==='savings'?state.data.savings:state.data.retirement}
function itemLabel(r){return `${r.company}${r.product?' · '+r.product:''}`}
function setupCompareSelects(){const rows=compareRows();const opts=rows.map((r,i)=>`<option value="${i}">${esc(itemLabel(r))}</option>`).join('');$('#compare-a').innerHTML=opts;$('#compare-b').innerHTML=opts;$('#compare-b').value=String(Math.min(1,rows.length-1));renderCompare()}
function compareMetrics(r){const s=state.compareType==='retirement'?$('#compare-scheme').value:null;return [{label:'3년 수익률',value:returnOf(r,'3',s),format:pct,better:'high'},{label:'5년 수익률',value:returnOf(r,'5',s),format:pct,better:'high'},{label:'10년 수익률',value:returnOf(r,'10',s),format:pct,better:'high'},{label:state.compareType==='savings'?'평균 수수료율':'총비용부담률',value:feeOf(r,s),format:pct,better:'low'},{label:'적립금',value:reserveOf(r,s),format:money,better:'high'}]}
function renderCompare(){if(!state.data)return;const rows=compareRows();if(!$('#compare-a').options.length)return setupCompareSelects();const a=rows[Number($('#compare-a').value)]||rows[0],b=rows[Number($('#compare-b').value)]||rows[1]||rows[0];if(!a||!b)return;const cards=[a,b].map((r,i)=>{const m=compareMetrics(r);return `<article class="compare-card"><span class="tag">COMPARE ${i?'B':'A'}</span><h3>${esc(r.company)}</h3><p>${esc(r.product||`${r.area} · 퇴직연금 사업자`)}</p><div class="compare-stat-grid">${m.slice(0,4).map(x=>`<div class="compare-stat"><span>${x.label}</span><strong>${x.format(x.value)}</strong></div>`).join('')}</div></article>`}).join('');$('#compare-cards').innerHTML=cards;const am=compareMetrics(a),bm=compareMetrics(b);$('#compare-bars').innerHTML=am.map((x,i)=>{const av=Math.abs(x.value),bv=Math.abs(bm[i].value),mx=Math.max(av,bv,1);return `<div class="comparison-row"><span>${x.label}</span><div class="compare-bar"><i style="width:${av/mx*100}%"></i><em>A · ${x.format(x.value)}</em></div><div class="compare-bar b"><i style="width:${bv/mx*100}%"></i><em>B · ${bm[i].format(bm[i].value)}</em></div></div>`}).join('');}
$$('[data-compare-type]').forEach(b=>b.addEventListener('click',()=>{$$('[data-compare-type]').forEach(x=>x.classList.toggle('active',x===b));state.compareType=b.dataset.compareType;$('#compare-scheme-wrap').hidden=state.compareType==='savings';$('#compare-a').innerHTML='';$('#compare-b').innerHTML='';setupCompareSelects()}));
['compare-a','compare-b','compare-scheme'].forEach(id=>$(`#${id}`).addEventListener('change',renderCompare));

function calculateTax(){const type=$('#income-type').value,income=Math.max(0,Number($('#income').value)||0),saving=Math.max(0,Number($('#saving-contribution').value)||0),irp=Math.max(0,Number($('#irp-contribution').value)||0),threshold=type==='salary'?5500:4500,rate=income<=threshold?.165:.132,savingEligible=Math.min(saving,600),irpEligible=Math.min(irp,Math.max(0,900-savingEligible)),eligible=savingEligible+irpEligible,total=saving+irp,credit=eligible*rate,remaining=Math.max(0,900-eligible);$('#tax-credit').textContent=`${num.format(Math.round(credit*10000))}원`;$('#tax-rate').textContent=`적용 공제율 ${(rate*100).toFixed(1)}% · 지방소득세 포함 추정`;$('#eligible-contribution').textContent=`${num.format(eligible)}만원`;$('#excess-contribution').textContent=`${num.format(Math.max(0,total-eligible))}만원`;$('#tax-progress-bar').style.width=`${Math.min(100,eligible/900*100)}%`;$('#tax-guide').textContent=remaining?`공제 한도까지 ${num.format(remaining)}만원을 추가 납입할 수 있습니다.`:'연금계좌 합산 세액공제 한도를 채웠습니다.';}
$('#income-type').addEventListener('change',()=>{$('#income-label').textContent=$('#income-type').value==='salary'?'총급여액':'종합소득금액';calculateTax()});['income','saving-contribution','irp-contribution'].forEach(id=>$(`#${id}`).addEventListener('input',calculateTax));

async function init(){try{const res=await fetch('./data/pensions.json',{cache:'no-store'});if(!res.ok)throw new Error();state.data=await res.json();$('#loading').hidden=true;$('#count-savings').textContent=`${num.format(state.data.savings.length)}개`;$('#count-retirement').textContent=`${num.format(state.data.retirement.length)}개`;$('#period-summary').textContent=state.data.periods.savings;$('#hero-period').textContent=state.data.periods.savings;$('#updated-summary').textContent=new Date(state.data.updatedAt).toLocaleDateString('ko-KR');fillSelect($('#savings-area'),areasFor(state.data.savings));fillSelect($('#retirement-area'),areasFor(state.data.retirement));renderSavings();renderRetirement();setupCompareSelects();calculateTax();const hash=location.hash.replace('#','');if(['savings','retirement','compare','tax'].includes(hash))showView(hash)}catch(e){$('#loading').hidden=true;$('#error').hidden=false}}
init();
